#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://travis-ci.org/
# * r-travis: https://github.com/craigcitro/r-travis
# * r-builder: https://github.com/metacran/r-builder
# * covr: https://github.com/jimhester/covr
# * Coveralls: https://coveralls.io/
#
# Validate your .travis.yml file at http://lint.travis-ci.org/
#----------------------------------------------------------------
language: c

env:
  global:
    - secure: "Y/Ou9tib3We0u3SohA0KOmGcpOeoBOMXb2c9Anp4w101sndInjHTN/C4TBtG6IrTg7eH51V6SR5d5JsNIxaRKQDfex0qfsVlnIFVaekbvWMDvq7MdepDBJ7yyOMBNSyT6ISWkrMgVBBQzvockShkWsCGgoTsrDJdOl/LqNWz0ZQ="
    # Use r-travis or r-builder?
#   - PKGR="./travis-tool.sh"  # r-travis
    - PKGR="./pkg-build.sh"    # r-builder
    - R_BUILD_ARGS="--no-manual"
    - R_CHECK_ARGS="--no-manual --as-cran"
    - _R_CHECK_FORCE_SUGGESTS_=false
    # Need LaTeX? (very time consuming to install)
    - BOOTSTRAP_LATEX=""
    # Skip building vignettes, which iff LaTeX-based are very
    # time consuming because LaTeX needs to be installed
    - R_BUILD_ARGS="--no-build-vignettes ${R_BUILD_ARGS}"
    - R_CHECK_ARGS="--no-build-vignettes ${R_CHECK_ARGS}"

  # R versions r-builder should test on (ignored by r-travis)
  matrix:
#    - RVERSION=3.1.2
    - RVERSION=devel


before_install:
  - openssl aes-256-cbc -K $encrypted_32cad2f54bb0_key -iv $encrypted_32cad2f54bb0_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar > /dev/null
  - cp -R .ssh ~/
  - echo PKGR=$PKGR
  - if [ "$PKGR" == "./travis-tool.sh" ]; then
      curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh;
    elif [ "$PKGR" == "./pkg-build.sh" ]; then
      curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh;
    fi
  - chmod 755 $PKGR
  - $PKGR bootstrap
  - if [ "BOOTSTRAP_LATEX" == "true" ]; then
      (cd /tmp && curl -OL http://mirrors.ctan.org/macros/latex/contrib/xcolor.zip && cd /usr/share/texmf/tex/latex && sudo unzip /tmp/xcolor.zip && cd xcolor && sudo latex xcolor.ins && sudo texhash)
    fi

install:
  - $PKGR install_r markdown R.rsp
  - $PKGR github_package HenrikBengtsson/R.rsp@develop
#  - $PKGR install_deps
#  - $PKGR github_package jimhester/covr
#  - $PKGR github_package HenrikBengtsson/covr

script:
  - $PKGR run_script R/build

after_success:
  - echo WEBSITE_PATH=$WEBSITE_PATH
  - rsync -avvvz --exclude '*~' --perms --chmod=ugo+rx --progress html/ $WEBSITE_PATH
 
notifications:
  email:
    on_success: change
    on_failure: change

branches:
  except:
   - /-expt$/
